"""Builds the /model/features catalog from the frozen 86-feature contract.

Source of truth: ``daily_pipeline/utils/contracts/champion_86_features.json``
(``feature_prune.kept_features``) -- the exact columns the champion model
was trained and is scored on (see Milestone 5/metrics_summary.json).

For each feature we report:

- ``displayName`` / ``unit`` / ``source`` -- derived from the real ERA5 /
  Sentinel-2 / Sentinel-5P / SRTM-DEM variable each key names (standard
  physical units for those products; no invented labels).
- ``min`` / ``max`` / ``defaultValue`` -- populated only when we have a real
  basis for them: either (a) a mathematical identity (sin/cos terms are
  exactly bounded to [-1, 1]; percentages/fractions are bounded to their
  definition), or (b) empirical stats computed from the static DEM grid that
  ships with the repo (``era5_grid_dem_features.parquet``). Every other
  feature (live ERA5 weather, Sentinel EO, engineered fire-neighbor context)
  legitimately depends on the daily pipeline's live feature pull, which this
  offline catalog does not have -- those bounds are left ``null`` rather
  than guessed. A future iteration can populate them from a real historical
  feature summary once one is generated by the pipeline.
- ``editableInScenario`` -- False for static/structural/calendar features
  (terrain, lat/lon, day-of-year/month encodings) that a "what-if" scenario
  cannot meaningfully move; True for the dynamic weather/vegetation/
  satellite/fire-context features scenario controls are meant to perturb.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Any

import pandas as pd

from .config import ensure_pipeline_on_path, get_feature_contract, get_pipeline_config

SOURCE_ERA5 = "era5-reanalysis"
SOURCE_SENTINEL2 = "sentinel2-surface-reflectance"
SOURCE_SENTINEL5P = "sentinel5p-atmosphere"
SOURCE_DEM = "srtm-dem"
SOURCE_ENGINEERED = "daily-feature-pipeline"
SOURCE_FIRE_CONTEXT = "firms-neighbor-context"
SOURCE_CALENDAR = "calendar"

# Static structural/calendar keys -- not meaningful scenario levers.
_NOT_EDITABLE = {
    "elevation", "slope", "aspect_sin", "aspect_cos", "tri", "tpi",
    "orographic_index", "hillshade", "latitude", "longitude",
    "day_of_year_sin", "day_of_year_cos", "month_sin", "month_cos",
}

# Indices exactly bounded to [-1, 1] by their mathematical definition
# (sin/cos terms, or normalized-difference spectral indices).
_UNIT_CIRCLE_BOUNDED = {
    "wind_dir_sin", "aspect_sin", "aspect_cos",
    "day_of_year_sin", "day_of_year_cos", "month_sin", "month_cos",
    "s2n_NDMI_mean", "s2n_NBR_mean", "s2n_NDWI_mean",
}
# Bounded to [0, 100] (percentage) or [0, 1] (fraction) by definition.
_PERCENT_BOUNDED = {"s2n_cloud_percentage": (0.0, 100.0)}
_FRACTION_BOUNDED = {"s2n_valid_fraction": (0.0, 1.0)}
# Non-negative counts (no known upper bound).
_NONNEGATIVE_COUNTS = {
    "fire_neighbor_count_lag2", "fire_neighbor_count_7d_lag2",
    "fire_upwind_count_7d_lag2", "fire_downwind_count_7d_lag2",
    "fire_crosswind_count_7d_lag2", "fire_distance_weighted_count_lag2",
    "fire_distance_weighted_count_7d_lag2",
}

_DISPLAY_OVERRIDES = {
    "t2m_mean": "2m Air Temperature (mean)",
    "t2m_max": "2m Air Temperature (max)",
    "t2m_min": "2m Air Temperature (min)",
    "d2m_mean": "2m Dewpoint Temperature (mean)",
    "sp_mean": "Surface Pressure (mean)",
    "wind_dir_sin": "Wind Direction (sine)",
    "swvl1_mean": "Soil Water Layer 1 (mean)",
    "swvl2_mean": "Soil Water Layer 2 (mean)",
    "swvl1": "Soil Water Layer 1",
    "rh_mean": "Relative Humidity (mean)",
    "vpd_kpa": "Vapor Pressure Deficit",
    "i10fg_max": "10m Wind Gust (max)",
    "wind_speed_mean": "Wind Speed (mean)",
    "tp_sum_mm": "Total Precipitation Sum",
    "soil_moisture_index": "Soil Moisture Index",
    "cvh_mean": "High Vegetation Cover (mean)",
    "cvl_mean": "Low Vegetation Cover (mean)",
    "lai_hv_mean": "Leaf Area Index, High Vegetation (mean)",
    "lai_lv_mean": "Leaf Area Index, Low Vegetation (mean)",
    "blh_mean": "Boundary Layer Height (mean)",
    "t2m_max_7d": "2m Air Temperature Max (7-day)",
    "tp_sum_7d": "Total Precipitation Sum (7-day)",
    "wind_speed_max_7d": "Wind Speed Max (7-day)",
    "rh_min_7d": "Relative Humidity Min (7-day)",
    "swvl1_mean_7d": "Soil Water Layer 1 (7-day mean)",
    "i10fg_max_7d": "10m Wind Gust Max (7-day)",
    "elevation": "Elevation",
    "slope": "Slope",
    "aspect_sin": "Aspect (sine)",
    "aspect_cos": "Aspect (cosine)",
    "tri": "Terrain Ruggedness Index",
    "tpi": "Topographic Position Index",
    "orographic_index": "Orographic Index",
    "hillshade": "Hillshade",
    "s2n_cloud_percentage": "Sentinel-2 Cloud Percentage",
    "s2n_valid_fraction": "Sentinel-2 Valid-Pixel Fraction",
    "s2n_NDMI_mean": "NDMI (mean)",
    "s2n_NBR_mean": "NBR (mean)",
    "s2n_NDWI_mean": "NDWI (mean)",
    "s2n_EVI_mean": "EVI (mean)",
    "s5n_s5p_aai_mean": "UV Aerosol Index (mean)",
    "s5n_s5p_aai_max": "UV Aerosol Index (max)",
    "s5n_s5p_co_mean": "Atmospheric CO Column (mean)",
    "s5n_s5p_co_max": "Atmospheric CO Column (max)",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "day_of_year_sin": "Day of Year (sine)",
    "day_of_year_cos": "Day of Year (cosine)",
    "month_sin": "Month (sine)",
    "month_cos": "Month (cosine)",
    "heat_soil_deficit_interaction": "Heat x Soil-Moisture-Deficit Interaction",
    "wind_gust_ratio": "Wind Gust Ratio",
    "ignition_dry_windy_index": "Ignition Dry-Windy Index",
    "vpd_short_long_trend": "VPD Short-vs-Long-Term Trend",
    "fire_context_vpd_interaction": "Fire-Neighbor x VPD Interaction",
    "fire_context_dry_windy_interaction": "Fire-Neighbor x Dry-Windy Interaction",
}

_S2_BAND_NAMES = {"B2": "Blue", "B3": "Green", "B4": "Red", "B8": "NIR", "B11": "SWIR1", "B12": "SWIR2"}


def _display_name(key: str) -> str:
    if key in _DISPLAY_OVERRIDES:
        return _DISPLAY_OVERRIDES[key]
    for band, label in _S2_BAND_NAMES.items():
        if key == f"s2n_{band}_mean":
            return f"Sentinel-2 {label} ({band}, mean)"
        if key == f"s2n_{band}_std":
            return f"Sentinel-2 {label} ({band}, std dev)"
    if key.startswith("fire_"):
        return key.replace("_", " ").replace("lag2", "(2-day lag)").title()
    for suffix, label in (
        ("_max_14d", " Max (14-day)"),
        ("_max_30d", " Max (30-day)"),
        ("_min_14d", " Min (14-day)"),
        ("_min_30d", " Min (30-day)"),
        ("_mean_14d", " Mean (14-day)"),
        ("_mean_30d", " Mean (30-day)"),
        ("_sum_14d", " Sum (14-day)"),
        ("_sum_30d", " Sum (30-day)"),
        ("_anomaly_30d", " Anomaly (30-day)"),
    ):
        if key.endswith(suffix):
            base = key[: -len(suffix)]
            return f"{_DISPLAY_OVERRIDES.get(base, base.replace('_', ' ').title())}{label}"
    return key.replace("_", " ").title()


def _source(key: str) -> str:
    if key.startswith(("t2m_", "d2m_", "sp_", "wind_", "swvl", "soil_", "cvh_", "cvl_", "lai_", "blh_", "i10fg_", "tp_", "rh_", "vpd_")):
        return SOURCE_ERA5
    if key.startswith("s2n_"):
        return SOURCE_SENTINEL2
    if key.startswith("s5n_"):
        return SOURCE_SENTINEL5P
    if key.startswith("fire_"):
        return SOURCE_FIRE_CONTEXT
    if key in {"elevation", "slope", "aspect_sin", "aspect_cos", "tri", "tpi", "orographic_index", "hillshade"}:
        return SOURCE_DEM
    if key in {"latitude", "longitude"}:
        return SOURCE_DEM
    if key in {"day_of_year_sin", "day_of_year_cos", "month_sin", "month_cos"}:
        return SOURCE_CALENDAR
    return SOURCE_ENGINEERED


def _unit(key: str) -> str | None:
    if key.startswith("t2m_") or key.startswith("d2m_"):
        return "K"
    if key.startswith("sp_"):
        return "Pa"
    if key.startswith("swvl"):
        return "m3/m3"
    if key.startswith("tp_"):
        return "mm"
    if key.startswith(("wind_speed", "i10fg_")):
        return "m/s"
    if key.startswith("rh_"):
        return "%"
    if key.startswith("vpd_"):
        return "kPa"
    if key.startswith("blh_"):
        return "m"
    if key.startswith(("cvh_", "cvl_")):
        return "fraction"
    if key.startswith(("lai_",)):
        return "m2/m2"
    if key == "elevation":
        return "m"
    if key == "slope":
        return "deg"
    if key in {"latitude", "longitude"}:
        return "deg"
    if key == "s2n_cloud_percentage":
        return "%"
    if key == "s2n_valid_fraction":
        return "fraction"
    if key.startswith("s5n_s5p_co"):
        return "mol/m2"
    if key.startswith("fire_") and "count" in key:
        return "cells"
    return None


def _bounds(key: str, dem_stats: dict[str, tuple[float, float, float]]) -> tuple[float | None, float | None, float | None]:
    """Returns (min, max, default) or (None, None, None) when unknown."""
    if key in _UNIT_CIRCLE_BOUNDED:
        return (-1.0, 1.0, 0.0)
    if key in _PERCENT_BOUNDED:
        lo, hi = _PERCENT_BOUNDED[key]
        return (lo, hi, 0.0)
    if key in _FRACTION_BOUNDED:
        lo, hi = _FRACTION_BOUNDED[key]
        return (lo, hi, 1.0)
    if key in _NONNEGATIVE_COUNTS:
        return (0.0, None, 0.0)
    if key in dem_stats:
        lo, hi, mean = dem_stats[key]
        return (lo, hi, mean)
    return (None, None, None)


def _step_for(lo: float | None, hi: float | None) -> float | None:
    if lo is None or hi is None:
        return None
    span = hi - lo
    if span <= 0:
        return None
    # A round-ish increment: ~1% of the real observed range.
    raw = span / 100
    return round(raw, 4) if raw < 1 else round(raw, 2)


@lru_cache(maxsize=1)
def _dem_stats() -> dict[str, tuple[float, float, float]]:
    ensure_pipeline_on_path()
    from paths import resolve_path

    cfg = get_pipeline_config()
    path = resolve_path(cfg, "dem_local")
    if not path.is_file():
        return {}
    frame = pd.read_parquet(path)
    stats: dict[str, tuple[float, float, float]] = {}
    for col in ("elevation", "slope", "tri", "tpi", "hillshade", "latitude", "longitude"):
        if col in frame.columns:
            series = frame[col].astype(float)
            stats[col] = (float(series.min()), float(series.max()), float(series.mean()))
    return stats


def build_feature_catalog() -> list[dict[str, Any]]:
    contract = get_feature_contract()
    dem_stats = _dem_stats()
    keys = contract["feature_prune"]["kept_features"]
    catalog: list[dict[str, Any]] = []
    for key in keys:
        lo, hi, default = _bounds(key, dem_stats)
        catalog.append(
            {
                "key": key,
                "display_name": _display_name(key),
                "type": "number",
                "unit": _unit(key),
                "source": _source(key),
                "min": lo,
                "max": hi,
                "step": _step_for(lo, hi),
                "default_value": default,
                "editable_in_scenario": key not in _NOT_EDITABLE,
            }
        )
    return catalog
